[project]
name = "mcp-sport"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "andrequeiroz2", email = "andrequeiroz.com@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=4.0.5",
]

[project.scripts]
mcp-sport = "mcp_sport:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
